export default {
  IS_OFFLINE: process.env.IS_OFFLINE ? Boolean(process.env.IS_OFFLINE) : false,
  NODE_ENV: process.env.NODE_ENV || 'local',
  ORIGIN: process.env.ORIGIN || '*',
  JWT_SECRET: process.env.JWT_SECRET || 'secret',
  JWT_EXPIRATION_TIME: process.env.JWT_EXPIRATION_TIME || '3600',
  CLOUD_S3_BUCKET: process.env.CLOUD_S3_BUCKET || '',
  CLOUD_S3_BUCKET_UPLOADS: process.env.CLOUD_S3_BUCKET ? `${process.env.CLOUD_S3_BUCKET}/uploads` : '',
  CLOUD_ACCESS_KEY_ID: process.env.CLOUD_ACCESS_KEY_ID || '',
  CLOUD_SECRET_ACCESS_KEY: process.env.CLOUD_SECRET_ACCESS_KEY || '',
  CLOUD_S3_REGION: process.env.CLOUD_S3_REGION || 'us-east-1',
  DATABASE_HOST: process.env.DATABASE_HOST || 'localhost',
  DATABASE_PORT: process.env.DATABASE_PORT || '3306',
  DATABASE_USER: process.env.DATABASE_USER || 'root',
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD || 'root',
  DATABASE_NAME: process.env.DATABASE_NAME || '',
};
